### ISSUE TITLE
CD triggers

### ISSUE THREAD

**Issue by aidanheerdegen** [ACCESS-NRI/intake-dataframe-catalog#26]
The CD workflow looks very neat and clean, but I'm curious about the workflow triggers for CD. Specifically the pypi deployment:

https://github.com/ACCESS-NRI/intake-dataframe-catalog/actions/runs/4932562837/workflow#L8
```yaml
    if: github.repository == 'ACCESS-NRI/intake-dataframe-catalog' && github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
```
checks the repo name. Why? Is this considered a good security practice?

The `conda` deployment depends on the `pypi` deployment, but appears to be independent of it. You could run them in parallel for speed, or if parallel is undesirable, running them in the same step would avoid the overhead of set up. You don't get a nice clean separation though. 

Don't get me wrong, I don't necessarily think you should change to running in one step, but just thought it was reasonable to talk about the pros and cons.

**Comment by dougiesquire** [comment]
Thanks @aidanheerdegen.

> checks the repo name. Why? Is this considered a good security practice?

This is to prevent it from running in forks.

> The conda deployment depends on the pypi deployment, but appears to be independent of it

It's not clear from just looking at the workflow, bu the conda distribution actually builds from the PyPI distribution (that's specified in `.conda/meta.yaml`) so it is dependent on a successful upload to PyPI. I did this so I could be confident that the PyPI and conda distributions were the same

**Comment by aidanheerdegen** [comment]
Thanks for the info.
